# Generated by Django 4.0.7 on 2022-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient',
            name='bp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='pulse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='respiration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='symptoms_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='symptoms_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='symptoms_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='temperature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inpatient',
            name='category',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True),
        ),
    ]
