# Generated by Django 4.0.7 on 2022-09-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_inpatient_bp_inpatient_pulse_inpatient_respiration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inpatient',
            old_name='category',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='inpatient',
            name='quantity',
        ),
    ]
