# Generated by Django 4.0.7 on 2022-09-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_category_inpatient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient',
            name='activity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
