# Generated by Django 4.0.7 on 2022-09-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_inpatient_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inpatient',
            options={'verbose_name_plural': 'Inpatient'},
        ),
        migrations.RemoveField(
            model_name='inpatient',
            name='activity',
        ),
    ]
