# Generated by Django 4.0.7 on 2022-09-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_inpatient_options_remove_inpatient_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inpatient',
            options={},
        ),
        migrations.AddField(
            model_name='inpatient',
            name='admission_date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='bed_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='case',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='casuatly',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='credit_limit',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='date_of_birth',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='height',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='live_consultation',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='old_patient',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='reference',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='weight',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
