# Generated by Django 4.0.7 on 2022-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_inpatient_options_inpatient_admission_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inpatient',
            old_name='casuatly',
            new_name='consultant',
        ),
        migrations.AddField(
            model_name='inpatient',
            name='count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inpatient',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
